### ISSUE TITLE
Can a demo site be created? 

### ISSUE THREAD

**Issue by PSCourtney** [BrightsDays/one-ring-log#1]
I'd like to view this on a demo site please.

**Comment by BrightsDays** [comment]
I'm going through a difficult time right now, but I'll try to finish and publish the demo before this weekend.
This will actually be a very simple app for the warden to keep track of the adventure and magical items.

**Comment by PSCourtney** [comment]
Sorry to hear that. I just appreciate your work. The Cairn tracker is great.

**Comment by BrightsDays** [comment]
I made a demo, but it's like a pre-alpha - it looks and works bad at the same time :)
And it's better not to use a non-test email to create an account, I can tell you it's not secure right now.

But the basic idea is clear - you can create an adventure page for your One Ring party and share it with players (they don't need to log in, one of the adventures: https://brightsdays.github.io/one-ring-log/adventure?id=deb7bed8-5187-4c76-b688-c77f88d4b677). I'll add items, eye level, etc. in the future after lots of fixes and testing with the gaming group.
